# this file is to be used with the two commands
# ros2 run crazyflie_crtp gateway --ros-args --params-file params/audio_test.yaml
# ros2 run topic_plotter audio --ros-args --params-file params/audio_test.yaml
gateway:
  ros__parameters:
    send_audio_enable: 1
    min_freq: 1000
    max_freq: 2000
    delta_freq: 100 # not used without prop
    n_average: 5 # not used without snr
    filter_snr_enable: 0
    filter_prop_enable: 0
    window_type: 1
audio_plotter:
  ros__parameters:
    min_freq: 1000
    max_freq: 2000
