gateway:
  ros__parameters:
    send_audio_enable: 1
    min_freq: 4000
    max_freq: 4200
    delta_freq: 100 # not used without prop
    n_average: 5 # not used without snr
    bin_selection: 0
    filter_prop_enable: 0
    hover_height: 0.0
    turn_angle: 0
    land_velocity: 0.0
    move_distance: 0.0
    buzzer_effect: 0
    buzzer_freq: 0
