gateway:
  ros__parameters:
    send_audio_enable: 1
    min_freq: 1000
    max_freq: 5000
    delta_freq: 100 # not used without prop
    n_average: 1 # not used without snr
    filter_snr_enable: 1
    filter_prop_enable: 1
    buzzer_effect: 0
    buzzer_freq: 0
