repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/duembgen/scripts
    rev: v0.0.7 # Replace by any tag/version
    hooks:
      - id: remove-output
        language_version: python3 # Should be a command that runs python3.6+
