# Goal request:
uint32 timestamp # ROS timestamp in miliseconds
string command_name
float32 command_value 0.0
---
# Result 
float32 value 0
string message ""
---
# Feedback
float32 value 0 
string message ""
