// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.cs');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Přidat komentář";
Blockly.Msg.AUTH = "Please authorize this app to enable your work to be saved and to allow it to be shared by you.";  // untranslated
Blockly.Msg.CHANGE_VALUE_TITLE = "Změna hodnoty:";
Blockly.Msg.CHAT = "Chat with your collaborator by typing in this box!";  // untranslated
Blockly.Msg.CLEAN_UP = "Clean up Blocks";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "Skrýt bloky";
Blockly.Msg.COLLAPSE_BLOCK = "Skrýt blok";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "barva 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "barva 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "poměr";
Blockly.Msg.COLOUR_BLEND_TITLE = "smíchat";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Smíchá dvě barvy v daném poměru (0.0–1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://cs.wikipedia.org/wiki/Barva";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Vyberte barvu z palety.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "náhodná barva";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Zvolte barvu náhodně.";
Blockly.Msg.COLOUR_RGB_BLUE = "modrá";
Blockly.Msg.COLOUR_RGB_GREEN = "zelená";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "červená";
Blockly.Msg.COLOUR_RGB_TITLE = "barva s";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Vytvoř barvu se zadaným množstvím červené, zelené a modré.  Všechny hodnoty musí být mezi 0 a 100.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "vymanit se ze smyčky";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "pokračuj dalším opakováním smyčky";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Přeruš vnitřní smyčku.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Přeskoč zbytek této smyčky a pokračuj dalším opakováním.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Upozornění: Tento blok může být použit pouze uvnitř smyčky.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "pro každou položku %1 v seznamu %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Pro každou položku v seznamu nastavte do proměnné '%1' danou položku a proveďte nějaké operace.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "počítat s %1 od %2 do %3 po %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Nechá proměnnou \"%1\" nabývat hodnot od počátečního do koncového čísla po daném přírůstku a provádí s ní příslušné bloky.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Přidat podmínku do \"pokud\" bloku.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Přidej konečnou podmínku zahrnující ostatní případy do bloku pokud.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Přidej, odstraň či uspořádej sekce k přenastavení tohoto bloku pokud.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "jinak";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "nebo pokud";
Blockly.Msg.CONTROLS_IF_MSG_IF = "pokud";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Je-li hodnota pravda, proveď určité příkazy.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Je-li hodnota pravda, proveď první blok příkazů.  V opačném případě proveď druhý blok příkazů.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Je-li první hodnota pravdivá, proveď první blok příkazů. V opačném případě, je-li pravdivá druhá hodnota, proveď druhý blok příkazů.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Je-li první hodnota pravda, proveď první blok příkazů.  Je-li druhá hodnota pravda, proveď druhý blok příkazů.  Pokud žádná hodnota není pravda, proveď poslední blok příkazů.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://cs.wikipedia.org/wiki/Cyklus_for";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "udělej";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "opakovat %1 krát";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Proveď určité příkazy několikrát.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "opakovat dokud";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "opakovat když";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Dokud je hodnota nepravdivá, prováděj určité příkazy.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Dokud je hodnota pravdivá, prováděj určité příkazy.";
Blockly.Msg.DELETE_BLOCK = "Odstranit blok";
Blockly.Msg.DELETE_X_BLOCKS = "Odstranit %1 bloky";
Blockly.Msg.DISABLE_BLOCK = "Zakázat blok";
Blockly.Msg.DUPLICATE_BLOCK = "zdvojit";
Blockly.Msg.ENABLE_BLOCK = "Povolit blok";
Blockly.Msg.EXPAND_ALL = "Rozbalit bloky";
Blockly.Msg.EXPAND_BLOCK = "Rozbalení bloku";
Blockly.Msg.EXTERNAL_INPUTS = "vnější vstupy";
Blockly.Msg.HELP = "Nápověda";
Blockly.Msg.INLINE_INPUTS = "Vložené vstupy";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "vytvořit prázdný seznam";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Vrátí seznam nulové délky, který neobsahuje žádné datové záznamy";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "seznam";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Přidat, odebrat nebo změnit pořadí oddílů tohoto seznamu bloku.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "vytvořit seznam s";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Přidat položku do seznamu.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Vytvoř seznam s libovolným počtem položek.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "první";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# od konce";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "získat";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "získat a odstranit";
Blockly.Msg.LISTS_GET_INDEX_LAST = "poslední";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "náhodné";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "odstranit";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Vrátí první položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Vrátí položku z určené pozice v seznamu.  #1 je poslední položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Vrátí položku z určené pozice v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Vrátí poslední položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Vrátí náhodnou položku ze seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Odstraní a vrátí první položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Odstraní a vrátí položku z určené pozice v seznamu.  #1 je poslední položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Odstraní a vrátí položku z určené pozice v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Odstraní a vrátí poslední položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Odstraní a vrátí náhodnou položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Odstraní první položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Odstraní položku na konkrétním místu v seznamu. #1 je poslední položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Odebere položku na konkrétním místě v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Odstraní poslední položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Odstraní náhodou položku v seznamu.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "do # od konce";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "do #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "jako poslední";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "získat podseznam od první položky";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "získat podseznam od # od konce";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "získat podseznam od #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Vytvoří kopii určené části seznamu.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "najít první výskyt položky";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "najít poslední výskyt položky";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Returns the index of the first/last occurrence of the item in the list. Returns 0 if item is not found.";  // untranslated
Blockly.Msg.LISTS_INLIST = "v seznamu";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 je prázdné";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Vrátí hodnotu pravda, pokud je seznam prázdný.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "délka %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Vrací počet položek v seznamu.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "vytvoř seznam s položkou %1 opakovanou %1 krát";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Vytváří seznam obsahující danou hodnotu n-krát.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "jako";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "vložit na";
Blockly.Msg.LISTS_SET_INDEX_SET = "nastavit";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Vložit položku na začátek seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Vloží položku na určenou pozici v seznamu.  #1 je poslední položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Vloží položku na určenou pozici v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Připojí položku na konec seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Připojí položku náhodně do seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Nastaví první položku v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Nastaví položku na konkrétní místo v seznamu. #1 je poslední položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Nastaví položku na konkrétní místo v seznamu. #1 je první položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Nastaví poslední položku v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Nastaví náhodnou položku v seznamu.";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "make list from text";  // untranslated
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "make text from list";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Split text into a list of texts, breaking at each delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "with delimiter";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "nepravda";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Vrací pravda nebo nepravda.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "pravda";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://cs.wikipedia.org/wiki/Nerovnost_(matematika)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Vrátí hodnotu pravda, pokud se oba vstupy rovnají jeden druhému.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Navrátí hodnotu pravda, pokud první vstup je větší než druhý vstup.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Navrátí hodnotu pravda, pokud je první vstup větší a nebo rovný druhému vstupu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Navrátí hodnotu pravda, pokud je první vstup menší než druhý vstup.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Navrátí hodnotu pravda, pokud je první vstup menší a nebo rovný druhému vstupu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Vrátí hodnotu pravda, pokud se oba vstupy nerovnají sobě navzájem.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "není %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Navrátí hodnotu pravda, pokud je vstup nepravda. Navrátí hodnotu nepravda, pokud je vstup pravda.";
Blockly.Msg.LOGIC_NULL = "nula";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Vrátí nulovou hodnotu";
Blockly.Msg.LOGIC_OPERATION_AND = "a";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "nebo";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Vrátí hodnotu pravda, pokud oba dva vstupy jsou pravdivé.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Vrátí hodnotu pravda, pokud alespoň jeden ze vstupů má hodnotu pravda.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "je-li nepravda";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "je-li to pravda";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Zkontroluje podmínku v \"testu\". Když je podmínka pravda, vrátí hodnotu \"pokud pravda\"; v opačném případě vrátí hodnotu \"pokud nepravda\".";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://cs.wikipedia.org/wiki/Aritmetika";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Vrátí součet dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Vrátí podíl dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Vrátí rozdíl dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Vrátí součin dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Vrátí první číslo umocněné na druhé číslo.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://pt.wikipedia.org/wiki/Adi%C3%A7%C3%A3o";
Blockly.Msg.MATH_CHANGE_TITLE = "změnit %1 od %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Přičti číslo k proměnné '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Vraťte jednu z následujících konstant: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "omez %1 na rozmezí od %2 do %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Omezí číslo tak, aby bylo ve stanovených mezích (včetně).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "je dělitelné";
Blockly.Msg.MATH_IS_EVEN = "je sudé";
Blockly.Msg.MATH_IS_NEGATIVE = "je záporné";
Blockly.Msg.MATH_IS_ODD = "je liché";
Blockly.Msg.MATH_IS_POSITIVE = "je kladné";
Blockly.Msg.MATH_IS_PRIME = "je prvočíslo";
Blockly.Msg.MATH_IS_TOOLTIP = "Kontrola, zda je číslo sudé, liché, prvočíslo, celé, kladné, záporné nebo zda je dělitelné daným číslem. Vrací pravdu nebo nepravdu.";
Blockly.Msg.MATH_IS_WHOLE = "je celé";
Blockly.Msg.MATH_MODULO_HELPURL = "https://cs.wikipedia.org/wiki/Modul%C3%A1rn%C3%AD_aritmetika";
Blockly.Msg.MATH_MODULO_TITLE = "zbytek po dělení %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Vrátí zbytek po dělení dvou čísel.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "https://cs.wikipedia.org/wiki/Číslo";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Číslo.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "průměr v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "největší v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "medián v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "nejmenší v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modes of list";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "náhodná položka seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "směrodatná odchylka ze seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "suma seznamu";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Vrátí průměr (aritmetický průměr) číselných hodnot v seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Vrátí největší číslo v seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Vrátí medián seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Vrátí nejmenší číslo v seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Vrátí seznam nejčastějších položek seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Vrátí náhodnou položku ze seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Vrátí směrodatnou odchylku seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Vrátí součet všech čísel v seznamu.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "náhodné číslo mezi 0 (včetně) do 1";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Vrátí náhodné číslo mezi 0,0 (včetně) až 1,0";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "náhodné celé číslo od %1 do %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Vrací náhodné celé číslo mezi dvěma určenými mezemi, včetně mezních hodnot.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://cs.wikipedia.org/wiki/Zaokrouhlení";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "zaokrouhlit";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "zaokrouhlit dolu";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "zaokrouhlit nahoru";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Zaokrouhlit číslo nahoru nebo dolů.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://cs.wikipedia.org/wiki/Druhá_odmocnina";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolutní";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "druhá odmocnina";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Vrátí absolutní hodnotu čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Vrátí mocninu čísla e.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Vrátí přirozený logaritmus čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Vrátí desítkový logaritmus čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Vrátí zápornou hodnotu čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Vrátí mocninu čísla 10.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Vrátí druhou odmocninu čísla.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "acos";
Blockly.Msg.MATH_TRIG_ASIN = "arcsin";
Blockly.Msg.MATH_TRIG_ATAN = "arctan";
Blockly.Msg.MATH_TRIG_COS = "cos";
Blockly.Msg.MATH_TRIG_HELPURL = "https://cs.wikipedia.org/wiki/Goniometrická_funkce";
Blockly.Msg.MATH_TRIG_SIN = "sin";
Blockly.Msg.MATH_TRIG_TAN = "tan";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Vrátí arckosinus čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Vrátí arcsinus čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Vrátí arctangens čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Vrátí kosinus úhlu ve stupních.";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Vrátí sinus úhlu ve stupních.";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Vrátí tangens úhlu ve stupních.";
Blockly.Msg.ME = "Me";  // untranslated
Blockly.Msg.NEW_VARIABLE = "Nová proměnná...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Nový název proměnné:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "s:";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://cs.wikipedia.org/wiki/Funkce_(programov%C3%A1n%C3%AD)";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Spustí uživatelem definovanou funkci '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://cs.wikipedia.org/wiki/Funkce_(programov%C3%A1n%C3%AD)";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Spustí uživatelem definovanou funkci '%1' a použije její výstup.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "s:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Vytvořit '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "proveď něco";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "k provedení";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Vytvořit funkci bez výstupu.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "navrátit";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Vytvořit funkci s výstupem.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Upozornění: Tato funkce má duplicitní parametry.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Zvýraznit definici funkce";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Je-li hodnota pravda, pak vrátí druhou hodnotu.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Varování: Tento blok může být použit pouze uvnitř definici funkce.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "vstupní jméno:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "vstupy";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Odstranit komentář";
Blockly.Msg.RENAME_VARIABLE = "Přejmenovat proměnné...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Přejmenujte všechny proměnné '%1':";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "přidat text";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "do";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Přidá určitý text k proměnné '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "na malá písmena";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "na Počáteční Velká Písmena";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "na VELKÁ PÍSMENA";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Vrátí kopii textu s jinou velikostí písmen.";
Blockly.Msg.TEXT_CHARAT_FIRST = "získat první písmeno";
Blockly.Msg.TEXT_CHARAT_FROM_END = "získat # písmeno od konce";
Blockly.Msg.TEXT_CHARAT_FROM_START = "získat písmeno #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "v textu";
Blockly.Msg.TEXT_CHARAT_LAST = "získat poslední písmeno";
Blockly.Msg.TEXT_CHARAT_RANDOM = "získat náhodné písmeno";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Získat písmeno na konkrétní pozici.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Přidat položku do textu.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "spojit";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Přidat, odebrat nebo změnit pořadí oddílů tohoto textového bloku.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "do # písmene od konce";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "do písmene #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "do posledního písmene";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "v textu";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "získat podřetězec od prvního písmene";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "získat podřetězec od písmene # od konce";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "získat podřetězec od písmene #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Získat zadanou část textu.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "v textu";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "najít první výskyt textu";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "najít poslední výskyt textu";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Vrátí index prvního/posledního výskytu prvního textu v druhém textu.  Pokud text není nalezen, vrátí hodnotu 0.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 je prázdný";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Vrátí pravda pokud je zadaný text prázdný.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "vytvořit text s";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Vytvoří kousek textu spojením libovolného počtu položek.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "délka %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Vrátí počet písmen (včetně mezer) v zadaném textu.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "tisk %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Tisk zadaného textu, čísla nebo jiné hodnoty.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Výzva pro uživatele k zadání čísla.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Výzva pro uživatele k zadání nějakého textu.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "výzva k zadání čísla se zprávou";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "výzva k zadání textu se zprávou";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://cs.wikipedia.org/wiki/Textov%C3%BD_%C5%99et%C4%9Bzec";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Písmeno, slovo nebo řádek textu.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "odstranit mezery z obou stran";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "odstranit mezery z levé strany";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "odstranit mezery z pravé strany";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Vrátí kopii textu s odstraněnými mezerami z jednoho nebo obou konců.";
Blockly.Msg.THYMIO_ACTUATOR_COMM = "set IR communication to transmit to";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_COMM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_COMM_TOOLTIP = "Sets the IR communication value to send";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC = "set microphone threshold to";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC_TOOLTIP = "Sets the microphone threshold";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR = "set %1 motor speed to %2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_TOOLTIP = "Sets a motor speed on the robot";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_SET_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_SET_TOOLTIP = "Sets an actuator variable on the robot";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER = "set %1 timer period to %2 milliseconds";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_FIRST = "first";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_SECOND = "second";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_TOOLTIP = "Sets a timer period variable on the robot";  // untranslated
Blockly.Msg.THYMIO_ARITHMETIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ARITHMETIC_TOOLTIP = "Computes arithmetic expressions";  // untranslated
Blockly.Msg.THYMIO_BINARY = "%2 binary %1 %3";  // untranslated
Blockly.Msg.THYMIO_BINARY_AND = "and";  // untranslated
Blockly.Msg.THYMIO_BINARY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_BINARY_LEFT_SHIFT = "left shift";  // untranslated
Blockly.Msg.THYMIO_BINARY_OR = "or";  // untranslated
Blockly.Msg.THYMIO_BINARY_RIGHT_SHIFT = "right shift";  // untranslated
Blockly.Msg.THYMIO_BINARY_TOOLTIP = "Computes binary expressions";  // untranslated
Blockly.Msg.THYMIO_BINARY_XOR = "xor";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED = "%1 button touched";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_BACKWARD = "backward";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_CENTER = "center";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_FORWARD = "forward";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_TOOLTIP = "Checks if a button is pressed";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION = "%1 IR communication";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_DISABLE = "disable";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_ENABLE = "enable";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_TOOLTIP = "Controls the communication feature of the robot";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY = "declare %1 as array of size %2";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY_TOOLTIP = "Declares an array of a certain size";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON = "on %1 button %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_BACKWARD = "backward";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_CENTER = "center";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_FORWARD = "forward";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_PRESS = "touched";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_RELEASE = "released";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_TOOLTIP = "React to a button press or release event";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX = "on %1 sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND = "on %1 ground sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_BLACK = "black";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_TOOLTIP = "React to a ground proximity event";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_WHITE = "white";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_TOOLTIP = "React to a proximity event";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE = "on %1 received";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_COMM = "IR communication";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_RC = "remote control signal";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_TOOLTIP = "React to a receive event";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK = "on shock detected";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK_TOOLTIP = "React to a shock event";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND = "on sound %1";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_FINISHED = "finished playing";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_MIC = "intensity above threshold";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_TOOLTIP = "React to a sound event";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER = "on %1 timer expired";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_FIRST = "first";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_SECOND = "second";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_TOOLTIP = "React to an expired timer event";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE = "on %1 updated";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_ACC = "accelerometer";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_BUTTONS = "button values";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_MOTOR = "motor";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_PROX = "proximity sensors";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_TEMPERATURE = "temperature";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_TOOLTIP = "React to an update event";  // untranslated
Blockly.Msg.THYMIO_FOR_DO = "do";  // untranslated
Blockly.Msg.THYMIO_FOR_FOR = "for";  // untranslated
Blockly.Msg.THYMIO_FOR_FROM = "from";  // untranslated
Blockly.Msg.THYMIO_FOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_FOR_TO = "to";  // untranslated
Blockly.Msg.THYMIO_FOR_TOOLTIP = "Counts a variable up from a start to an end value";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY = "array %1 element %2";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY_TOOLTIP = "Gets the value of an array element";  // untranslated
Blockly.Msg.THYMIO_LED = "set %1 LED to %2";  // untranslated
Blockly.Msg.THYMIO_LED_BOTTOM_LEFT = "bottom left";  // untranslated
Blockly.Msg.THYMIO_LED_BOTTOM_RIGHT = "bottom right";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON = "set button LEDs to forward %1 right %2 backward %3 left %4";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON_TOOLTIP = "Sets the button LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE = "set circle LEDs to forward %1 forward right %2 right %3 backward right %4 backward %5 backward left %6 left %7 forward left %8";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE_TOOLTIP = "Sets the circle LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_OFF = "turn off %1";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BOTTOM_LEFT = "bottom left LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BOTTOM_RIGHT = "bottom right LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BUTTONS = "button LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_CIRCLE = "circle LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_MICROPHONE = "microphone LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_PROX_H = "horizontal proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_PROX_V = "ground proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_RC = "remote control LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TEMPERATURE = "temperature LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TOOLTIP = "Turns off a LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TOP = "top LED";  // untranslated
Blockly.Msg.THYMIO_LED_PROX = "set horizontal proximity LEDs to front left %1 front left/middle %2 front middle/left %3 front middle/right %4 front right/middle %5 front right %6 rear left %7 rear right %8";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND = "set ground proximity LEDs to left %1 right %2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND_TOOLTIP = "Sets the ground proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_TOOLTIP = "Sets the horizontal proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND = "set %1 LED to %2";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_RC = "remote control";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_SOUND = "microphone";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_TOOLTIP = "Sets the remote control and sound LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_RGB = "set %1 LED to red %2 green %3 blue %4";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_BOTTOM_LEFT = "bottom left";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_BOTTOM_RIGHT = "bottom right";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_TOOLTIP = "Sets a LED to a specified color by RGB values";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_TOP = "top";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE = "set temperature LEDs to red %1 blue %2";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE_TOOLTIP = "Sets the temperature LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_TOOLTIP = "Sets a LED to a specified color";  // untranslated
Blockly.Msg.THYMIO_LED_TOP = "top";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START = "start %1 with speed %2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_BACKWARD = "driving backward";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_FORWARD = "driving forward";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_SPINCCW = "spinning counterclockwise";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_SPINCW = "spinning clockwise";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TOOLTIP = "Starts the motors";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNBACKWARDLEFT = "turning backward left";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNBACKWARDRIGHT = "turning backward right";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNLEFT = "turning left";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNRIGHT = "turning right";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP = "stop motors";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP_TOOLTIP = "Stops the motors";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK = "%1 sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_TOOLTIP = "Checks if a proximity sensor is blocked";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK = "%1 ground sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_BLACK = "black";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_TOOLTIP = "Checks if a proximity sensor is blocked";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_WHITE = "white";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC = "accelerometer %1 value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_TOOLTIP = "Retrieves a accelerometer sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_X = "x";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_Y = "y";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_Z = "z";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM = "received IR communication value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM_TOOLTIP = "Retrieves the received IR communication value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC = "microphone intensity value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC_TOOLTIP = "Retrieves the microphone intensity value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR = "%1 motor speed";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_TOOLTIP = "Retrieves the speed of a motor";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX = "%1 proximity sensor closeness";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_GROUND_LEFT = "left ground";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_GROUND_RIGHT = "right ground";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_TOOLTIP = "Retrieves the closeness of a proximity sensor";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC = "received remote control %1 value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_ADDRESS = "address";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_COMMAND = "command";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_TOOLTIP = "Retrieves a remote control sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE = "temperature sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE_TOOLTIP = "Retrieves the temperature sensor value";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY = "set array %1 element %2 to %3";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY_TOOLTIP = "Sets the value of an array element";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE = "play %1 Hz note for %2 / 60 seconds";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE_TOOLTIP = "Plays a note of a frequency for a duration";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP = "stop playing sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP_TOOLTIP = "Stops playing sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM = "play %1 sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_ARROW = "arrow";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_CENTRAL = "central";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_COLLISION = "collision";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_SCARY = "scary";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_SHUTDOWN = "shutdown";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_STARTUP = "startup";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TARGET_DETECTED = "target detected";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TARGET_FRIENDLY = "target friendly";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TOOLTIP = "Plays a system sound";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_SUBROUTINE = "subroutine";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_TOOLTIP = "Defines subroutines";  // untranslated
Blockly.Msg.THYMIO_UNARY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_UNARY_TOOLTIP = "Performs unary operations";  // untranslated
Blockly.Msg.THYMIO_UNNARY = "%1 %2";  // untranslated
Blockly.Msg.THYMIO_UNNARY_ABSOLUTE = "absolute";  // untranslated
Blockly.Msg.THYMIO_UNNARY_BINARY_NOT = "binary not";  // untranslated
Blockly.Msg.THYMIO_UNNARY_NEGATIVE = "negative";  // untranslated
Blockly.Msg.THYMIO_VARIABLE_SET = "set %1 to %2";  // untranslated
Blockly.Msg.THYMIO_WHEN_DO = "do";  // untranslated
Blockly.Msg.THYMIO_WHEN_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_WHEN_TOOLTIP = "Check for a change of condition";  // untranslated
Blockly.Msg.THYMIO_WHEN_WHEN = "when";  // untranslated
Blockly.Msg.TODAY = "Dnes";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "položka";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Vytvořit \"nastavit %1\"";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Vrátí hodnotu této proměnné.";
Blockly.Msg.VARIABLES_SET = "nastavit %1 na %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Vytvořit \"získat %1\"";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Nastaví tuto proměnnou, aby se rovnala vstupu.";
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;