// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.hrx');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Kommentar hinzufüche";
Blockly.Msg.AUTH = "Weart ännre:";
Blockly.Msg.CHANGE_VALUE_TITLE = "Neie Variable...";
Blockly.Msg.CHAT = "Sprech mit unsrem Mitoorweiter doorrich renschreiwe von Text hier in den Kaste!";
Blockly.Msg.CLEAN_UP = "Clean up Blocks";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "Blocke zusammerfalte";
Blockly.Msg.COLLAPSE_BLOCK = "Block zusammerfalte";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "Farreb 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "mit Farreb 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "im Verhältniss";
Blockly.Msg.COLOUR_BLEND_TITLE = "misch";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Vermischt 2 Farwe mit konfigurierbare Farrebverhältniss (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://hrx.wikipedia.org/wiki/Farreb";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Wähl en Farreb von der Palett.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "zufälliche Farwe";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Wähl en Farreb noh dem Zufallsprinzip.";
Blockly.Msg.COLOUR_RGB_BLUE = "blau";
Blockly.Msg.COLOUR_RGB_GREEN = "grün";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "rot";
Blockly.Msg.COLOUR_RGB_TITLE = "Färreb mit";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Kreiere ene Farreb mit sellrbst definierte rot, grün und blau Wearte. All Wearte müsse zwischich 0 und 100 liehe.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "ausbreche aus der Schleif";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "mit der nächste Iteration fortfoohre aus der Schleifa";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Die umgebne Schleif beenne.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Die Oonweisung abbreche und mit der nächste Schleifiteration fortfoohre.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Warnung: Die block sollt nuar in en Schleif verwennet sin.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "Für Weart %1 aus der List %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Füahr en Oonweisung für jede Weart in der List aus und setzt dabei die Variable \"%1\" uff den aktuelle List Weart.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "Zähl %1 von %2 bis %3 mit %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Zähl die Variable \"%1\" von enem Startweart bis zu enem Zielweart und füahrefür jede Weart en Oonweisung aus.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "En weitre Bedingung hinzufüche.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "En orrer Bedingung hinzufüche, füahrt en Oonweisung aus falls ken Bedingung zutrifft.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Hinzufüche, entferne orrer sortiere von Sektione";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "orrer";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "orrer wenn";
Blockly.Msg.CONTROLS_IF_MSG_IF = "wenn";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Wenn en Bedingung woahr (true) ist, dann füahr en Oonweisung aus.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Wenn en Bedingung woahr (true) ist, dann füahr die earscht Oonweisung aus.  Ansonscht füahr die zwooite Oonweisung aus.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Wenn der erschte Bedingung woahr (true) ist, dann füahr die erschte Oonweisung aus.  Orrer wenn die zwooite Bedingung woahr (true) ist, dann füahr die zwooite Oonweisung aus.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Wenn der erscht Bedingung woahr (true) ist, dann füahr die erschte Oonweisung aus.  Orrer wenn die zwooite Bedingung woahr (true) ist, dann füahr die zwooite Oonweisung aus.  Falls ken der beide Bedingungen woahr (true) ist, dann füahr die dritte Oonweisung aus.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://hrx.wikipedia.org/wiki/For-Schleif";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "mach";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "wiederhol %1 mol";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "En Oonweisung meahrfach ausführe.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "Repetiere bis";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "Repetier solang";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Füahr die Oonweisung solang aus wie die Bedingung falsch (false) ist.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Füahr die Oonweisung solang aus wie die Bedingung woahr (true) ist.";
Blockly.Msg.DELETE_BLOCK = "Block lösche";
Blockly.Msg.DELETE_X_BLOCKS = "Block %1 lösche";
Blockly.Msg.DISABLE_BLOCK = "Block deaktivieren";
Blockly.Msg.DUPLICATE_BLOCK = "Kopieren";
Blockly.Msg.ENABLE_BLOCK = "Block aktivieren";
Blockly.Msg.EXPAND_ALL = "Blocke expandiere";
Blockly.Msg.EXPAND_BLOCK = "Block entfalte";
Blockly.Msg.EXTERNAL_INPUTS = "External Inputsexterne Ingänge";
Blockly.Msg.HELP = "Hellef";
Blockly.Msg.INLINE_INPUTS = "interne Ingänge";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "Generier/erzeich en leear List";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Generier/erzeich en leear List ohne Inhalt.";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "List";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Hinzufüche, entferne und sortiere von Elemente.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "Erzeich List mit";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "En Element zur List hinzufüche.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Generier/erzeich en List mit konfigurierte Elemente.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "earste";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "#te von hinne";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "Nehm";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "Nehm und entfern";
Blockly.Msg.LISTS_GET_INDEX_LAST = "letzte";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "zufälliches";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "Entfern";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Extrahiert das earste Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Extrahiert das #1te Element der List sei End.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Extrahiert das #1te Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Extrahiert das letzte Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Extrahiert en zufälliches Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Extrahiert und entfernt das earste Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Extrahiert und entfernt das #1te Element der List sei End.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Extrahiert und entfernt das #1te Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Extrahiert und entfernt das letzte Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Extrahiert und entfernt en zufälliches Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Entfernt das earste Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Entfernt das #1te Element der List sei End.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Entfernt das #1te Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Entfernt das letzte Element von der List.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Entfernt en zufälliches Element von der List.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "zu # vom End";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "zu #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "zum Letzte";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "hol Unnerliste vom Earste";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "hol Unnerliste von # vom End";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "hol Unnerlist von #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Generiert en Kopie von en definierte Tel von en List.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "Such earstes Voarkommniss";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "Such letztes Voarkommniss";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Sucht die Position (index) von en Element in der List Gebt 0 zurück wenn nixs gefunn woard.";
Blockly.Msg.LISTS_INLIST = "in der List";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 ist leear?";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Ist woahr (true), wenn die List leear ist.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "länge %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Die Oonzoohl von Elemente in der List.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "Erzich List mit Element %1 wiederhol das %2 mol";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Erzeicht en List mit en variable Oonzoohl von Elemente";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "uff";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "tue ren setz an";
Blockly.Msg.LISTS_SET_INDEX_SET = "setz";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Tut das Element an en Oonfang von en List ren setze.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Tut das Element ren setze an en definierte Position an en List.  #1 ist das letzte Element.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Tut das Element ren setze an en definierte Position an en List.  #1 ist das earschte Element.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Oonhängt das Element zu en List sei End.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Tut das Element zufällich an en List ren setze.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Sets the first item in a list.Setzt das earschte Element an en list.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Setzt das Element zu en definierte Position an en List. #1 ist das letzte Element.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Setzt das Element zu en definierte Stell in en List.  #1 ist das earschte Element.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Setzt das letzte Element an en List.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Setzt en zufälliches Element an en List.";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "make list from text";  // untranslated
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "make text from list";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Join a list of texts into one text, separated by a delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Split text into a list of texts, breaking at each delimiter.";  // untranslated
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "with delimiter";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "falsch";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Ist entweder woahr (true) orrer falsch (false)";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "woahr";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://hrx.wikipedia.org/wiki/Vergleich_%28Zahlen%29";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Ist woahr (true) wenn beide Wearte identisch sind.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Ist woahr (true) wenn der erschte Weart grösser als der zwooite Weart ist.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Ist woahr (true) wenn der erschte Weart grösser als orrer gleich gross wie zwooite Weart ist.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Ist woahr (true) wenn der earschte Weart klener als der zwooite Weart ist.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Ist woahr (true) wenn der earscht Weart klener als orrer gleich gross wie zwooite Weart ist.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Ist woahr (true) wenn beide Wearte unnerschiedlich sind.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "net %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Ist woahr (true) wenn der Ingäweweart falsch (false) ist.  Ist falsch (false) wenn der Ingäweweart woahr (true) ist.";
Blockly.Msg.LOGIC_NULL = "null";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Is NULL.";
Blockly.Msg.LOGIC_OPERATION_AND = "und";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "orrer";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Ist woahr (true) wenn beide Wearte woahr (true) sind.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Ist woahr (true) wenn en von der beide Wearte woahr (true) ist.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "wenn falsch";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "wenn woahr";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Üwerprüft en Bedingung \"test\". Wenn die Bedingung woahr ist weerd der \"wenn woahr\" Weart zurückgeb, annerfalls der \"wenn falsch\" Weart";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://hrx.wikipedia.org/wiki/Grundrechenoort";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Ist die Summe zwooier Wearte.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Ist der Quotient zwooier Wearte.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Ist die Differenz zwooier Wearte.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Ist das Produkt zwooier Wearte.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Ist der earschte Weart potenziert mit dem zoiten Weart.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://hrx.wikipedia.org/wiki/Inkrement_und_Dekrement";
Blockly.Msg.MATH_CHANGE_TITLE = "mach höcher / erhöhe %1 um %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Addiert en Weart zur Variable \"%1\" hinzu.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://hrx.wikipedia.org/wiki/Mathematische_Konstante";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Mathematische Konstante wie: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…) oder ∞ (unendlich).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "begrenze %1 von %2 bis %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Begrenzt den Weartebereich mittels von / bis Wearte. (inklusiv)";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "ist telbar/kann getelt sin doorrich";
Blockly.Msg.MATH_IS_EVEN = "ist grood";
Blockly.Msg.MATH_IS_NEGATIVE = "ist negativ";
Blockly.Msg.MATH_IS_ODD = "ist ungrood";
Blockly.Msg.MATH_IS_POSITIVE = "ist positiv";
Blockly.Msg.MATH_IS_PRIME = "ist en Primenzoohl";
Blockly.Msg.MATH_IS_TOOLTIP = "Üwerprüft ob en Zoohl grood, ungrood, en Primenzoohl, ganzzoohlich, positiv, negativ orrer doorrich en zwooite Zoohl telbar ist.  Gebt woahr (true) orrer falsch (false) zurück.";
Blockly.Msg.MATH_IS_WHOLE = "ganze Zoohl";
Blockly.Msg.MATH_MODULO_HELPURL = "https://hrx.wikipedia.org/wiki/Modulo";
Blockly.Msg.MATH_MODULO_TITLE = "Rest von %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Der Rest noh en Division.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://hrx.wikipedia.org/wiki/Zoohl";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "En Zoohl.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "Mittelweart en List";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "Maximalweart en List";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "Median von en List";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "Minimalweart von en List";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "Restweart von en List";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "Zufallsweart von en List";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "Standart/Padrong Abweichung von en List";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "Summe von en List";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Ist der Doorrichschnittsweart von aller Wearte in en List.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Ist der grösste Weart in en List.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Ist der Zentralweart von aller Wearte in en List.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Ist der klenste Weart in en List.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Findt den am häifichste voarkommend Weart in en List.  Falls ken Weart öftersch voarkomme als all annre, weard die originale List zurückgeche";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Geb en Zufallsweart aus der List zurück.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Ist die standartiesierte/padronisierte Standartabweichung/Padrongabweichung von aller Wearte in der List";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Ist die Summ aller Wearte in en List.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://hex.wikipedia.org/wiki/Zufallszoohle";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "Zufallszoohl (0.0 -1.0)";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Generier/erzeich en Zufallszoohl zwischich 0.0 (inklusiv) und 1.0 (exklusiv).";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://hrx.wikipedia.org/wiki/Zufallszahlen";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "ganzoohlicher Zufallswearte zwischich %1 bis %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Generier/erzeich en ganzähliche Zufallsweart zwischich zwooi Wearte (inklusiv).";
Blockly.Msg.MATH_ROUND_HELPURL = "https://hrx.wikipedia.org/wiki/Runden";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "runde";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "ab runde";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "uff runde";
Blockly.Msg.MATH_ROUND_TOOLTIP = "En Zoohl uff orrer ab runde.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://hrx.wikipedia.org/wiki/Quadratwoorzel";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "Absolutweart";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "Quadratwoorzel";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Ist der Absolutweart von en Weart.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Ist Weart von der Exponentialfunktion von en Weart.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Ist der natüarliche Logarithmus von en Weart.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Ist der dekoodische Logarithmus von en Weart.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Negiert en Weart.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Rechnet 10 hoch Ingäbweart.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Ist die Qudratwoorzel von en Weart.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://hrx.wikipedia.org/wiki/Trigonometrie";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Ist der Arcuscosinus von en Ingabweart.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Ist der Arcussinus von en Ingäbweart.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Ist der Arcustangens von en Ingäbweart.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Ist der Cosinus von en Winkel.";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Ist der Sinus von en Winkel.";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Ist der Tangens von en Winkel.";
Blockly.Msg.ME = "Ich";
Blockly.Msg.NEW_VARIABLE = "Neie Variable...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Die neie Variable sei Noome:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "mit:";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://hrx.wikipedia.org/wiki/Prozedur_%28Programmierung%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Ruf en Funktionsblock ohne Rückgäweart uff.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://hrx.wikipedia.org/wiki/Prozedur_%28Programmierung%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Ruf en Funktionsblock mit Rückgäbweart uff.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "mit:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Generier/erzeich \"Uffruf %1\"";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "Funktionsblock";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "zu";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "En Funktionsblock ohne Rückgäbweart.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "geb zurück";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "En Funktionsblock mit Rückgäbweart.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Warnung: die Funktionsblock hot doppelt Parameter.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Markiear Funktionsblock";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Wenn der earste Weart woahr (true) ist, Geb den zwooite Weart zurück.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Warnung: Der Block därref nuar innich en Funktionsblock genutzt sin.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "Markiear Funktionsblock";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Generier/erzeich \"Uffruf %1\"";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "Parameter";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Variable:";
Blockly.Msg.REMOVE_COMMENT = "Kommentar entferne";
Blockly.Msg.RENAME_VARIABLE = "Die neie Variable sei Noome:";
Blockly.Msg.RENAME_VARIABLE_TITLE = "All \"%1\" Variable umbenenne in:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "Text oonhänge";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "An";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Text an die Variable \"%1\" oonhänge.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "umwandle in klenbuchstoobe";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "umwandle in Wörter";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "umwandle in GROSSBUCHSTOOBE";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Wandelt Schreibweise von Texte um, in Grossbuchstoobe, Klenbuchstoobe orrer den earste Buchstoob von jedes Wort gross und die annre klen.";
Blockly.Msg.TEXT_CHARAT_FIRST = "hol earschte Buchstoob";
Blockly.Msg.TEXT_CHARAT_FROM_END = "hol Buchstoob # von End";
Blockly.Msg.TEXT_CHARAT_FROM_START = "hol Buchstoob #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "in Text";
Blockly.Msg.TEXT_CHARAT_LAST = "hol letztes Wort";
Blockly.Msg.TEXT_CHARAT_RANDOM = "hol zufälliches Buchstoob";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Extrahiear en Buchstoob von en spezifizierte Position.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "En Element zum Text hinzufüche.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "verbinne";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Hinzufüche, entfernne und sortiere von Elemente.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "bis #te Buchstoob von hinne";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "bis Buchstoob #te";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "bis letzte Buchstoob";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "in Text";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "earschte Buchstoob";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "hol #te Buchstoob von hinne";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "hol substring Buchstoob #te";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Schickt en bestimmstes Tel von dem Text retuar.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "im Text";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "Such der Begriff sein earstes Voarkommniss";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "Suche der Begriff sein letztes Vorkommniss.";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Findt das earste / letzte Voarkommniss von en Suchbegriffes in enem Text.  Gebt die Position von dem Begriff orrer 0 zurück.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 ist leer?";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Ist woahr (true), wenn der Text leer ist.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "Erstell Text aus";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Erstellt en Text doorrich das verbinne von mehre Textelemente.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "läng %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Die Oonzoohl von Zeiche in enem Text. (inkl. Leerzeiche)";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "Ausgäb %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Geb den Inhalt von en Variable aus.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Frocht den Benutzer noh en Zoohl.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Frocht den Benutzer noh enem Text.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "Frächt noh Zoohl mit Hinweis";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "Frocht noh Text mit Hinweis";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)https://hrx.wikipedia.org/wiki/Zeichenkette";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "En Buchstoob, Text orrer Satz.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "entfern Leerzeiche von Oonfang und End Seite";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "entferne Leerzeiche von Oonfang Seite";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "entferne Leerzeiche von End Seite von";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Entfernt Leerzeiche vom Oonfang und / orrer End von en Text.";
Blockly.Msg.THYMIO_ACTUATOR_COMM = "set IR communication to transmit to";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_COMM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_COMM_TOOLTIP = "Sets the IR communication value to send";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC = "set microphone threshold to";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC_TOOLTIP = "Sets the microphone threshold";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR = "set %1 motor speed to %2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_TOOLTIP = "Sets a motor speed on the robot";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_SET_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_SET_TOOLTIP = "Sets an actuator variable on the robot";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER = "set %1 timer period to %2 milliseconds";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_FIRST = "first";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_SECOND = "second";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_TOOLTIP = "Sets a timer period variable on the robot";  // untranslated
Blockly.Msg.THYMIO_ARITHMETIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ARITHMETIC_TOOLTIP = "Computes arithmetic expressions";  // untranslated
Blockly.Msg.THYMIO_BINARY = "%2 binary %1 %3";  // untranslated
Blockly.Msg.THYMIO_BINARY_AND = "and";  // untranslated
Blockly.Msg.THYMIO_BINARY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_BINARY_LEFT_SHIFT = "left shift";  // untranslated
Blockly.Msg.THYMIO_BINARY_OR = "or";  // untranslated
Blockly.Msg.THYMIO_BINARY_RIGHT_SHIFT = "right shift";  // untranslated
Blockly.Msg.THYMIO_BINARY_TOOLTIP = "Computes binary expressions";  // untranslated
Blockly.Msg.THYMIO_BINARY_XOR = "xor";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED = "%1 button touched";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_BACKWARD = "backward";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_CENTER = "center";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_FORWARD = "forward";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_TOOLTIP = "Checks if a button is pressed";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION = "%1 IR communication";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_DISABLE = "disable";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_ENABLE = "enable";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_TOOLTIP = "Controls the communication feature of the robot";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY = "declare %1 as array of size %2";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY_TOOLTIP = "Declares an array of a certain size";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON = "on %1 button %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_BACKWARD = "backward";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_CENTER = "center";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_FORWARD = "forward";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_PRESS = "touched";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_RELEASE = "released";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_TOOLTIP = "React to a button press or release event";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX = "on %1 sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND = "on %1 ground sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_BLACK = "black";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_TOOLTIP = "React to a ground proximity event";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_WHITE = "white";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_TOOLTIP = "React to a proximity event";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE = "on %1 received";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_COMM = "IR communication";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_RC = "remote control signal";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_TOOLTIP = "React to a receive event";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK = "on shock detected";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK_TOOLTIP = "React to a shock event";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND = "on sound %1";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_FINISHED = "finished playing";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_MIC = "intensity above threshold";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_TOOLTIP = "React to a sound event";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER = "on %1 timer expired";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_FIRST = "first";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_SECOND = "second";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_TOOLTIP = "React to an expired timer event";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE = "on %1 updated";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_ACC = "accelerometer";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_BUTTONS = "button values";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_MOTOR = "motor";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_PROX = "proximity sensors";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_TEMPERATURE = "temperature";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_TOOLTIP = "React to an update event";  // untranslated
Blockly.Msg.THYMIO_FOR_DO = "do";  // untranslated
Blockly.Msg.THYMIO_FOR_FOR = "for";  // untranslated
Blockly.Msg.THYMIO_FOR_FROM = "from";  // untranslated
Blockly.Msg.THYMIO_FOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_FOR_TO = "to";  // untranslated
Blockly.Msg.THYMIO_FOR_TOOLTIP = "Counts a variable up from a start to an end value";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY = "array %1 element %2";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY_TOOLTIP = "Gets the value of an array element";  // untranslated
Blockly.Msg.THYMIO_LED = "set %1 LED to %2";  // untranslated
Blockly.Msg.THYMIO_LED_BOTTOM_LEFT = "bottom left";  // untranslated
Blockly.Msg.THYMIO_LED_BOTTOM_RIGHT = "bottom right";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON = "set button LEDs to forward %1 right %2 backward %3 left %4";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON_TOOLTIP = "Sets the button LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE = "set circle LEDs to forward %1 forward right %2 right %3 backward right %4 backward %5 backward left %6 left %7 forward left %8";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE_TOOLTIP = "Sets the circle LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_OFF = "turn off %1";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BOTTOM_LEFT = "bottom left LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BOTTOM_RIGHT = "bottom right LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BUTTONS = "button LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_CIRCLE = "circle LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_MICROPHONE = "microphone LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_PROX_H = "horizontal proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_PROX_V = "ground proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_RC = "remote control LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TEMPERATURE = "temperature LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TOOLTIP = "Turns off a LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TOP = "top LED";  // untranslated
Blockly.Msg.THYMIO_LED_PROX = "set horizontal proximity LEDs to front left %1 front left/middle %2 front middle/left %3 front middle/right %4 front right/middle %5 front right %6 rear left %7 rear right %8";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND = "set ground proximity LEDs to left %1 right %2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND_TOOLTIP = "Sets the ground proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_TOOLTIP = "Sets the horizontal proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND = "set %1 LED to %2";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_RC = "remote control";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_SOUND = "microphone";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_TOOLTIP = "Sets the remote control and sound LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_RGB = "set %1 LED to red %2 green %3 blue %4";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_BOTTOM_LEFT = "bottom left";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_BOTTOM_RIGHT = "bottom right";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_TOOLTIP = "Sets a LED to a specified color by RGB values";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_TOP = "top";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE = "set temperature LEDs to red %1 blue %2";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE_TOOLTIP = "Sets the temperature LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_TOOLTIP = "Sets a LED to a specified color";  // untranslated
Blockly.Msg.THYMIO_LED_TOP = "top";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START = "start %1 with speed %2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_BACKWARD = "driving backward";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_FORWARD = "driving forward";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_SPINCCW = "spinning counterclockwise";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_SPINCW = "spinning clockwise";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TOOLTIP = "Starts the motors";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNBACKWARDLEFT = "turning backward left";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNBACKWARDRIGHT = "turning backward right";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNLEFT = "turning left";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNRIGHT = "turning right";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP = "stop motors";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP_TOOLTIP = "Stops the motors";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK = "%1 sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_TOOLTIP = "Checks if a proximity sensor is blocked";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK = "%1 ground sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_BLACK = "black";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_TOOLTIP = "Checks if a proximity sensor is blocked";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_WHITE = "white";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC = "accelerometer %1 value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_TOOLTIP = "Retrieves a accelerometer sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_X = "x";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_Y = "y";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_Z = "z";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM = "received IR communication value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM_TOOLTIP = "Retrieves the received IR communication value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC = "microphone intensity value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC_TOOLTIP = "Retrieves the microphone intensity value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR = "%1 motor speed";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_TOOLTIP = "Retrieves the speed of a motor";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX = "%1 proximity sensor closeness";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_GROUND_LEFT = "left ground";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_GROUND_RIGHT = "right ground";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_TOOLTIP = "Retrieves the closeness of a proximity sensor";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC = "received remote control %1 value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_ADDRESS = "address";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_COMMAND = "command";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_TOOLTIP = "Retrieves a remote control sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE = "temperature sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE_TOOLTIP = "Retrieves the temperature sensor value";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY = "set array %1 element %2 to %3";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY_TOOLTIP = "Sets the value of an array element";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE = "play %1 Hz note for %2 / 60 seconds";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE_TOOLTIP = "Plays a note of a frequency for a duration";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP = "stop playing sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP_TOOLTIP = "Stops playing sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM = "play %1 sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_ARROW = "arrow";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_CENTRAL = "central";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_COLLISION = "collision";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_SCARY = "scary";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_SHUTDOWN = "shutdown";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_STARTUP = "startup";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TARGET_DETECTED = "target detected";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TARGET_FRIENDLY = "target friendly";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TOOLTIP = "Plays a system sound";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_SUBROUTINE = "subroutine";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_TOOLTIP = "Defines subroutines";  // untranslated
Blockly.Msg.THYMIO_UNARY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_UNARY_TOOLTIP = "Performs unary operations";  // untranslated
Blockly.Msg.THYMIO_UNNARY = "%1 %2";  // untranslated
Blockly.Msg.THYMIO_UNNARY_ABSOLUTE = "absolute";  // untranslated
Blockly.Msg.THYMIO_UNNARY_BINARY_NOT = "binary not";  // untranslated
Blockly.Msg.THYMIO_UNNARY_NEGATIVE = "negative";  // untranslated
Blockly.Msg.THYMIO_VARIABLE_SET = "set %1 to %2";  // untranslated
Blockly.Msg.THYMIO_WHEN_DO = "do";  // untranslated
Blockly.Msg.THYMIO_WHEN_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_WHEN_TOOLTIP = "Check for a change of condition";  // untranslated
Blockly.Msg.THYMIO_WHEN_WHEN = "when";  // untranslated
Blockly.Msg.TODAY = "Today";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "Element";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Generier/erzeiche \"Schreibe %1\"";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Gebt der Variable sein Weart zurück.";
Blockly.Msg.VARIABLES_SET = "Schreib %1 zu %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Generier/erzeich \"Lese %1\"";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Setzt en Variable sei Weart.";
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;